// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0emXf08aRaWp_4Vg7Qt8U9RcU4tHwRHI',
    appId: '1:627448212576:web:1f8e9abf5b5ed2ab2fe705',
    messagingSenderId: '627448212576',
    projectId: 'weerbidena-4c20f',
    authDomain: 'weerbidena-4c20f.firebaseapp.com',
    storageBucket: 'weerbidena-4c20f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3JOXW4E4XuMx0j-GEdQRURJzE1WiG7CY',
    appId: '1:627448212576:android:6f09fb6a23473b742fe705',
    messagingSenderId: '627448212576',
    projectId: 'weerbidena-4c20f',
    storageBucket: 'weerbidena-4c20f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0emXf08aRaWp_4Vg7Qt8U9RcU4tHwRHI',
    appId: '1:627448212576:web:4c94c028c70389a22fe705',
    messagingSenderId: '627448212576',
    projectId: 'weerbidena-4c20f',
    authDomain: 'weerbidena-4c20f.firebaseapp.com',
    storageBucket: 'weerbidena-4c20f.firebasestorage.app',
  );
}
